name: commit
on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:

env:
  ZIG_VERSION: 0.13.0
  BAZELISK_VERSION: 1.25.0

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'master')}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Zig Format
        run: zig fmt --check  $(find . -name "*.zig" -print | while read file; do git check-ignore -q "$file" || echo "$file"; done | xargs)

      # - name: No Autofix
      #   run: find . -name "*.zig" -print | while read file; do git check-ignore -q "$file" || (grep -q "// autofix" "$file" && echo "$file"); done | grep -q . ; [ 1 -eq $? ]

      - name: Setup Bazel
        run: |
          wget https://github.com/bazelbuild/bazelisk/releases/download/v${{ env.BAZELISK_VERSION }}/bazelisk-linux-amd64 -O ~/bin/bazel
          chmod +x ~/bin/bazel
          echo "$HOME/bin" >> "$GITHUB_PATH"
      
      - name: ZML / bazel mod explain
        run: bazel mod explain

      - name: ZML / bazel mod graph
        run: bazel mod graph

      - name: ZML / bazel query //...
        run: bazel query //... -- -//runtimes/neuron/...

      - name: ZML / bazel build //...
        run: bazel build --config=debug --verbose_failures //... -- -//runtimes/neuron/...

      - name: ZML / bazel test //...
        run: bazel test --config=debug --verbose_failures --keep_going --test_output=streamed --test_tag_filters=-no_ci //... -- -//runtimes/neuron/...

      - name: Examples / bazel mod explain
        working-directory: examples/
        run: bazel mod explain

      - name: Examples / bazel mod graph
        working-directory: examples/
        run: bazel mod graph

      - name: Examples / bazel query //...
        working-directory: examples/
        run: bazel query //...

      - name: Examples / bazel build //...
        working-directory: examples/
        run: bazel build --config=debug --verbose_failures --build_tag_filters=-no_ci //...

      - name: Examples / bazel test //...
        working-directory: examples/
        run: bazel test --config=debug --verbose_failures --keep_going --test_output=streamed --build_tag_filters=-no_ci --test_tag_filters=-no_ci //...
